spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/main
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    overwrite-existing-jobs: false
#    properties:
#      org:
#        quartz:
#          scheduler:
#            instanceName: scheduler
#            instanceId: AUTO
#          jobStore:
#            dataSource: scheduler
#            class: org.quartz.impl.jdbcjobstore.JobStoreTX
#            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
#            clusterCheckinInterval: 5000
#            isClustered: true
#          dataSource:
#            scheduler:
#              driver: com.mysql.cj.jdbc.Driver
#              URL: jdbc:mysql://127.0.0.1:3306/scheduler
#              user: root
#              password: root
#              maxConnections: 5
